@baseUrl = http://localhost:3001


## Rota Doctors

### Listar os médicos 
GET {{baseUrl}}/doctors/

### Pesquisar Doctor
GET {{baseUrl}}/doctors?name=Martins

### Inserir doctor
POST {{baseUrl}}/doctors/
Content-Type: application/json

{
   "name": "João Silva",
   "specialty": "Pediatra",
   "icon": "M"
}

### Alterar doctor
PUT {{baseUrl}}/doctors/7
Content-Type: application/json

{
    "name": "Dr João Silva",
    "specialty": "Pediatra",
    "icon": "M"
}

### Exclir doctor
DELETE {{baseUrl}}/doctors/2

##Rota Users

### Inserir usuário
POST {{baseUrl}}/users/register
Content-Type: application/json

{
   "name": "João Martins",
   "email": "joaol@test.com",
   "password": "123456"
}

### Login usuário
POST {{baseUrl}}/users/login
Content-Type: application/json

{
   "email": "miguel@test.com",
   "password": "123456"
}