@baseUrl = http://localhost:3001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJpYXQiOjE3Mjk1MTM0NTEsImV4cCI6MTczOTUxMzQ1MH0.ERLmMOMhU1XiI7IEFbUuDHnU51nI3ITTuM4daiCOeEQ


## Rota Doctors

### Listar os médicos 
GET {{baseUrl}}/doctors/
Authorization: Bearer {{token}} 

### Pesquisar Doctor
GET {{baseUrl}}/doctors?name=Martins

### Inserir doctor
POST {{baseUrl}}/doctors/
Content-Type: application/json

{
   "name": "João Silva",
   "specialty": "Pediatra",
   "icon": "M"
}

### Alterar doctor
PUT {{baseUrl}}/doctors/7
Content-Type: application/json

{
    "name": "Dr João Silva",
    "specialty": "Pediatra",
    "icon": "M"
}

### Exclir doctor
DELETE {{baseUrl}}/doctors/3

### Serviços 
GET {{baseUrl}}/doctors/6/services
Authorization: Bearer {{token}}

### Appointments 
GET {{baseUrl}}/appointments
Authorization: Bearer {{token}}

### Appointments 
POST {{baseUrl}}/appointments
Content-Type: application/json
Authorization: Bearer {{token}}

### Exclir appointment
DELETE {{baseUrl}}/appointments/5
Authorization: Bearer {{token}}

##Rota Users

### Inserir usuário
POST {{baseUrl}}/users/register
Content-Type: application/json

{
   "name": "Mario Martins",
   "email": "mario@test.com",
   "password": "123456"
}

### Login usuário
POST {{baseUrl}}/users/login
Content-Type: application/json

{
   "email": "miguel@test.com",
   "password": "123456"
}

### User Profile
GET  {{baseUrl}}/users/profile
Authorization: Bearer {{token}}